version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test
          command: |
            sudo npm install -g newman
            newman run New_Collection.postman_collection.json 
            newman -version
            pwd
            
workflows:
  default:
    jobs:
      - run_test
